---
Name: nswdpc-typesense-cms
---
SilverStripe\CMS\Model\SiteTree:
  extensions:
    TypesenseSearchData: NSWDPC\Typesense\CMS\Extensions\SiteTreeSearchResult
    RecordChangeHandler: NSWDPC\Search\Typesense\Extensions\RecordChangeHandler
ElliotSawyer\SilverstripeTypesense\Typesense:
  collections:
    SilverStripe\CMS\Model\SiteTree:
      name: 'Pages (default)'
      fields:
        - { name: Title, type: string, sort: true }
        - { name: MenuTitle, type: string, sort: true }
        - { name: Content, type: string, optional: true }
        - { name: Link, type: string, index: false, optional: true}
NSWDPC\Typesense\CMS\Models\TypesenseSearchPage:
  extensions:
    # scoped search support
    - 'NSWDPC\Search\Typesense\Extensions\SearchScope'
